<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Part;

/**
 * BuildingSetRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingKitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByPart(Part $part)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('building_kit')
            ->from('AppBundle:BuildingKit', 'building_kit')
            ->innerJoin('building_kit.parts', 'parts')
            ->where('parts.part = :id')->setParameter('id', $part->getId());

        return $qb->getQuery()->getResult();
    }
}
