<?php

namespace AppBundle\Repository;

/**
 * PartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartRepository extends \Doctrine\ORM\EntityRepository
{
}
