<?php

namespace AppBundle\Repository;

/**
 * Part_BuildingKitRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Part_BuildingKitRepository extends \Doctrine\ORM\EntityRepository
{
}
