<?php

namespace AppBundle\Imagine\Loader;

use Liip\ImagineBundle\Binary\Loader\StreamLoader;

class RemoteStreamLoader extends StreamLoader
{
    public function __construct($wrapperPrefix, $context = null)
    {
        dump($wrapperPrefix);

        parent::__construct($wrapperPrefix, $context);
    }

    public function find($path)
    {
        dump($path);

        return parent::find($path); // TODO: Change the autogenerated stub
    }
}